image: docker:18

variables:
  LATEST_VER_NGINX: docker.io/aguaragazu/lemp-nginx:latest
#  MAJOR_VER_NGINX: docker.io/aguaragazu/lemp-nginx:2
  MINOR_VER_NGINX: docker.io/aguaragazu/lemp-nginx:1.15.7
#  PATCH_VER_NGINX: docker.io/aguaragazu/lemp-nginx:2.3.1
  LATEST_VER_PHP: docker.io/aguaragazu/lemp-php:latest
#  MAJOR_VERR_PHP: docker.io/aguaragazu/lemp-php:2
  MINOR_VER_PHP: docker.io/aguaragazu/lemp-php:7.3
#  PATCH_VER_PHP: docker.io/aguaragazu/lemp-php:2.3.1


stages:
  - Build image
  - Push to Docker Hub

docker build:
  stage: Build image
  script:
  - docker info
  - docker-machine ip
  - docker build -t $LATEST_VER_NGINX -t $MINOR_VER_NGINX ./nginx
  - docker build -t $LATEST_VER_PHP -t $MINOR_VER_PHP ./php
#  - docker build -t $LATEST_VER_PHP -t $MAJOR_VER -t $MINOR_VER -t $PATCH_VER .

docker push:
  stage: Push to Docker Hub
  only:
  - master
  script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push $LATEST_VER_NGINX && docker image rm $LATEST_VER_NGINX
  - docker push $LATEST_VER_PHP && docker image rm $LATEST_VER_PHP
#  - docker push $MAJOR_VER && docker image rm $MAJOR_VER
  - docker push $MINOR_VER_NGINX && docker image rm $MINOR_VER_NGINX
  - docker push $MINOR_VER_PHP && docker image rm $MINOR_VER_PHP
#  - docker push $PATCH_VER && docker image rm $PATCH_VER